#!/bin/bash
# Package information
packager="My Email AT my email DOT com"
name=yoink-scripts
major_version=0
min_version=1
rel_version=0 
download=

# Some nice envionment variables
prev_dir=$PWD
srcfolder=$name-src
function get_source() {
	mkdir $srcfolder
	builtin cd $srcfolder
	wget $download
	file=$(ls)
	tar xf $file 
	rm $file
	file=$(ls)
	builtin cd $file
}

# Put all of your pre-compilation configuration here.
function config() {
	/bin/true	
}

# Put build commands here.
function build() {
	/bin/true
}

# Only change the line that says `make install`
function build_install() {
	mkdir /tmp/yoink/$name -p
	make install DESTDIR=/tmp/yoink/$name
}

function gen_tree(){
	currdir=$PWD
	builtin cd /tmp/yoink/$name
	find -not -name 'install.sh' -not -name '.TREE' -printf '%P\n' > .TREE;
	builtin cd $currdir
}

# Put post-build commands here.
function post_build(){
	[[ -f install.sh ]] && cp ./install.sh /tmp/yoink/$name
 	gen_tree	
	# Do not change any more lines.
	builtin cd /tmp/yoink/$name
	tar --exclude=./ --xform s:'./':: -czf ~/$name-$major_version.$min_version.$rel_version.tar.gz ./
	cd $prev_dir
	rm -rf /tmp/yoink/$name

}
export -f get_source
export -f config
export -f build
export -f build_install
export -f post_build
