#!/bin/bash

package_list=()

function check_file(){
    file="$1"
    { tar tvf "$file" .TREE ;} 2> /dev/null
    tree_status=$?
    if [[ "$tree_status" -ne 0 ]]; then
            echo "Package $file does not have a .TREE file? What are you doing?"
            exit 1
    fi
}

function install_packages(){
    for package in "${package_list}"; do
        check_file "$package"
        echo "Installing package from $package"
        tar xf $package -C /
    done
}

while [[ $# -gt 0 ]]; do
    opt="$1"
    shift;
    case "$opt" in
            "install")
                package_list=$@
                INSTALL=true
                break
                ;;
            "extract")
                echo "Method stub."
                break
                ;;
            *)
                echo "Invalid option."
                exit 1
                ;;
    esac
done

[[ $INSTALL ]] && install_packages






