#!/bin/bash

package_list=()
SKIP_CHECK=false
HAS_INSTALL=false
HAS_INSTALL_DOTSLASH=false
[[ $(id -u) -ne 0 ]] && echo "Must be root to use!" && exit 1

function check_file(){
    file="$1"
    { tar xf "$file" ./.TREE -C /tmp;} &> /dev/null
    tree_status=$?
    if [[ "$tree_status" -ne 0 ]]; then
	echo "Package $file does not have a .TREE file? What are you doing?"
	exit 1
    fi
    { tar xf "$file" ./install.sh -C /tmp;} &> /dev/null
    install_status=$?
    if [[ "$install_status" -eq 0 ]]; then
        HAS_INSTALL=true
	return
    fi

}



run_install(){
	file="$1"
	echo "Found install script for $(basename $file)"
	[[ $HAS_INSTALL ]] && chmod +x /tmp/install.sh && /tmp/install.sh ; rm /tmp/install.sh
}

function install_packages(){
    for package in "${package_list}"; do
        [[ ! $SKIP_CHECK = "true" ]] && check_file "$package"
        
	echo "Unpacking $(basename $package)"
	if [[ ! -z $YOINK_INSTALL_DIR ]]; then
		DIR=$YOINK_INSTALL_DIR
	else
		DIR=/
	fi
	        tar --dereference --exclude=./.TREE --exclude=./install.sh -xf $package -C $DIR

	[[ $HAS_INSTALL = "true" ]] && run_install $package
	echo "Done."
    done
}

while [[ $# -gt 0 ]]; do
    opt="$1"
    shift;
    case "$opt" in
            "install")
                package_list=$@
                INSTALL=true
                break
                ;;
            "--skip-check")
                    SKIP_CHECK=true
                    ;;
            "extract")
                echo "Method stub."
                break
                ;;
            *)
                echo "Invalid option."
                exit 1
                ;;
    esac
done

[[ $INSTALL ]] && install_packages






