#!/bin/bash
args=$@
progs_to_install=()
progs_shortname=()
MIRROR="gtower.ad.peasenet.com/yoinklinux"
for prog in ${args}; do
	package_line=`cat /usr/lib/yoink/yoink.db | grep $prog`;
	if [[ $? -eq 0 ]]; then
		new_package=`echo $package_line | cut -d ',' -f 2 | tr -d '\r'`;
		progs_to_install+=("$new_package");
		progs_shortname+=("$prog");
	fi
done

# Downloads the program.

#for installable in "${progs_to_install}"; do
#	echo Downloading ${progs_shortname[$installable]} - $program
#	$(wget -q -P /var/cache/yoink "$MIRROR/$program") 2>&1 >/dev/null
#	echo Done.
#done

for i in "${!progs_to_install[@]}"; do
	echo Downloading ${progs_shortname[$i]} - ${progs_to_install[i]};
	$(wget -q -P /var/cache/yoink "$MIRROR/$program") 2>&1 >/dev/null
	echo Done.
done

# Installs the program.

for i in "${!progs_to_install[@]}"; do 
	tarball=${progs_to_install[i]}
	yoink -a /var/cache/yoink/$tarball;
done
